"""add_endereco_cliente

Revision ID: 402582435db8
Revises: 650919ac59c6
Create Date: 2026-06-08 10:59:46.042716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '402582435db8'
down_revision: Union[str, None] = '650919ac59c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cep', sa.String(length=9), nullable=True))
    op.add_column('clientes', sa.Column('rua', sa.String(length=200), nullable=True))
    op.add_column('clientes', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('estado', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'estado')
    op.drop_column('clientes', 'cidade')
    op.drop_column('clientes', 'bairro')
    op.drop_column('clientes', 'complemento')
    op.drop_column('clientes', 'numero')
    op.drop_column('clientes', 'rua')
    op.drop_column('clientes', 'cep')
    # ### end Alembic commands ###
