"""add_configuracoes_and_agenda

Revision ID: 650919ac59c6
Revises: 4696dc8bd6a9
Create Date: 2026-06-08 10:42:41.846143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '650919ac59c6'
down_revision: Union[str, None] = '4696dc8bd6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('detalhe', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_id'), 'agenda', ['id'], unique=False)
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_chave'), 'configuracoes', ['chave'], unique=True)
    op.create_index(op.f('ix_configuracoes_id'), 'configuracoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracoes_id'), table_name='configuracoes')
    op.drop_index(op.f('ix_configuracoes_chave'), table_name='configuracoes')
    op.drop_table('configuracoes')
    op.drop_index(op.f('ix_agenda_id'), table_name='agenda')
    op.drop_table('agenda')
    # ### end Alembic commands ###
